import PDFDocument from 'pdfkit'
import PayslipLine from '../models/PayslipLine.js'

function money(value, currency = 'USD') {
  return `${currency} ${Number(value || 0).toFixed(2)}`
}

function formatDate(value) {
  return new Date(value).toISOString().slice(0, 10)
}

export async function renderPayslipPdf(payslip) {
  const lines = await PayslipLine.find({ payslipId: payslip._id }).sort({ sequence: 1 }).lean()
  const currency = payslip.contractSnapshot?.currency || 'USD'
  return new Promise((resolve, reject) => {
    const document = new PDFDocument({ margin: 56, size: 'A4' })
    const chunks = []
    document.on('data', (chunk) => chunks.push(chunk))
    document.on('end', () => resolve(Buffer.concat(chunks)))
    document.on('error', reject)

    document.fontSize(22).fillColor('#295448').text('PeoplePay360', { align: 'left' })
    document.moveDown(0.3).fontSize(16).fillColor('#17211b').text('Payslip')
    document.moveDown()
    document.fontSize(10).fillColor('#647067')
      .text(`Employee: ${payslip.employeeSnapshot?.name || 'Employee'}`)
      .text(`Employee number: ${payslip.employeeSnapshot?.employeeNumber || '-'}`)
      .text(`Department: ${payslip.employeeSnapshot?.department || '-'}`)
      .text(`Period: ${formatDate(payslip.periodStart)} to ${formatDate(payslip.periodEnd)}`)
      .text(`Status: ${payslip.status}`)
    document.moveDown()

    document.fontSize(10).fillColor('#17211b').text('Salary computation', { underline: true })
    document.moveDown(0.5)
    for (const line of lines) {
      document.fontSize(10).text(`${line.code}  ${line.name}  ${money(line.amount, currency)}`)
    }
    document.moveDown()
    document.fontSize(11).text(`Gross salary: ${money(payslip.grossAmount, currency)}`)
      .text(`Deductions: ${money(payslip.deductionAmount, currency)}`)
      .fontSize(14).fillColor('#295448').text(`Net salary: ${money(payslip.netAmount, currency)}`)
    document.moveDown()
    document.fontSize(9).fillColor('#647067').text('Generated by PeoplePay360 Payroll')
    document.end()
  })
}

export function payslipFileName(payslip) {
  const employeeNumber = payslip.employeeSnapshot?.employeeNumber || payslip.employeeId?.employeeNumber || payslip._id
  return `payslip-${employeeNumber}-${formatDate(payslip.periodStart)}.pdf`
}
